/********************************************************************************************
*                                                                                           *
*                                                                                           *
*                                                                                           *
* MIT License                                                                               *
*                                                                                           *
* Copyright (c) 2020 - 2026 BEAST                                                           *
*                                                                                           *
* Permission is hereby granted, free of charge, to any person obtaining a copy              *
* of this software and associated documentation files (the "Software"), to deal             *
* in the Software without restriction, including without limitation the rights              *
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell                 *
* copies of the Software, and to permit persons to whom the Software is                     *
* furnished to do so, subject to the following conditions:                                  *
*                                                                                           *
* The above copyright notice and this permission notice shall be included in all            *
* copies or substantial portions of the Software.                                           *
*                                                                                           *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR                *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,                  *
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE               *
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER                    *
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,             *
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE             *
* SOFTWARE.                                                                                 *
*********************************************************************************************
*/

#include "sppch.h"
#include "SClassDistReference.h"

#if defined(SAT_DIST)

//////////////////////////////////////////////////////////////////////////
// Okay so this is probably some of the worst code I've ever written however, it needs to be done
// for now, the idea of this is that we need to call StaticClass() so that the compiler does not strip out the SAT_X31_CREATE_AUTO_REG content
// However, I'm not entirely sure why the compiler does that anyway because when compiling on Dist with /DISTASDGB 
// and with /Od it still removes the functions, it seems to be because the target SClass is not directly referenced so the
// compiler tries to be smart and remove it, however the class is needed via our SObject system.
// So, we could dynamically load the RCRXXX functions.
// So this is a temporary solution to a (hopefully) temporary problem.
//
// This method could still exist if we ever use the BuildTool for the Engine, in that case this file could be automatically
// generated by SBT.
//
// TODO: ^^

// SClasses
#include "Saturn/AI/AIAgentEntity.h"
#include "Saturn/AI/BehaviourTree/AssetViewer/Nodes/BehaviourTreeNodeBase.h" 
#include "Saturn/AI/BehaviourTree/AssetViewer/Nodes/BehaviourTreeRootNode.h"
#include "Saturn/AI/BehaviourTree/AssetViewer/Nodes/BehaviourTreeSelectorNode.h"
#include "Saturn/AI/BehaviourTree/AssetViewer/Nodes/BehaviourTreeSequenceNode.h"
#include "Saturn/AI/BehaviourTree/AssetViewer/Nodes/BehaviourTreeTaskNode.h"
#include "Saturn/AI/BehaviourTree/Conditions/BehaviourTreeCondition.h"
#include "Saturn/AI/BehaviourTree/Conditions/BehaviourTreeMemoryCondition.h"
#include "Saturn/AI/BehaviourTree/Tasks/BehaviourTreeBaseTask.h"
#include "Saturn/AI/BehaviourTree/Tasks/BehaviourTreeCompositeTasks.h"
#include "Saturn/AI/BehaviourTree/Tasks/BehaviourTreeMoveToTask.h"
#include "Saturn/AI/BehaviourTree/Tasks/BehaviourTreePlaySoundTask.h"
#include "Saturn/AI/BehaviourTree/Tasks/BehaviourTreeWaitTask.h"
#include "Saturn/AI/Navigation/NavBoundsEntity.h"

#include "Saturn/Animation/AssetViewer/Graph/Animation/AnimGraphOutputNode.h"
#include "Saturn/Animation/AssetViewer/Graph/Animation/AnimGraphStateMachinePlayerNode.h"
#include "Saturn/Animation/AssetViewer/Graph/StateMachine/AnimGraphStateMachineOutNode.h"
#include "Saturn/Animation/AssetViewer/Graph/StateMachine/AnimGraphStateMachinePlayAnimNode.h"
#include "Saturn/Animation/AssetViewer/Graph/StateMachine/AnimGraphStateMachineStateNode.h"
#include "Saturn/Animation/AssetViewer/Graph/StateMachine/AnimGraphStateMachineTransitionNode.h"
#include "Saturn/Animation/AssetViewer/Graph/StateMachine/AnimGraphTransitionGraphNodes.h"

#include "Saturn/Animation/AssetViewer/Graph/Tasks/AnimGraphPlayAnimTask.h"
#include "Saturn/Animation/AssetViewer/Graph/Tasks/AnimGraphStateMachineStateTask.h"
#include "Saturn/Animation/AssetViewer/Graph/Tasks/AnimGraphTransitionTasks.h"
#include "Saturn/Animation/AssetViewer/Graph/Tasks/GraphTask.h"

#include "Saturn/Audio/SoundGraph/Tasks/SoundGraphTasks.h"
#include "Saturn/Audio/SoundGraph/Nodes/SoundGraphNodes.h"

#include "Saturn/GameFramework/Character.h"
#include "Saturn/GameFramework/Core/GameModule.h"

#include "Saturn/ImGui/MaterialAssetViewer/MaterialGraphNodes.h"

#include "Saturn/NodeEditor/NodeEditorBlueprintNode.h"
#include "Saturn/NodeEditor/NodeEditorHintNode.h"
#include "Saturn/NodeEditor/NodeEditorTaskBase.h"
#include "Saturn/NodeEditor/NodeEditorTreeNode.h"
#include "Saturn/NodeEditor/NodeEditorVariableNode.h"
#include "Saturn/NodeEditor/NodeEditorVariableTasks.h"

#include "Saturn/Scene/Entity.h"

namespace Saturn {

	// Reference all SClasses...
	void SClassDistReferencer::Reference()
	{
		AIAgentEntity::StaticClass();
		BehaviourTreeRootNode::StaticClass();
		BehaviourTreeSelectorNode::StaticClass();
		BehaviourTreeSequenceNode::StaticClass();
		BehaviourTreeTaskNode::StaticClass();
		BehaviourTreeCondition::StaticClass();
		BehaviourTreeMemoryCondition::StaticClass();
		BehaviourTreeWaitTask::StaticClass();
		BehaviourTreePlaySoundTask::StaticClass();
		BehaviourTreeMoveToTask::StaticClass();
		BehaviourTreeBaseTask::StaticClass();
		BehaviourTreeCompositeBaseTask::StaticClass();
		BehaviourTreeSequenceTask::StaticClass();
		BehaviourTreeSelectorTask::StaticClass();
	
		NavBoundsEntity::StaticClass();

		AnimGraphOutputNode::StaticClass();
		AnimGraphStateMachinePlayerNode::StaticClass();
		AnimGraphStateMachineOutNode::StaticClass();
		AnimGraphStateMachinePlayAnimNode::StaticClass();
		AnimGraphStateMachineStateNode::StaticClass();
		AnimGraphStateMachineTransitionNode::StaticClass();
		AnimGraphTransitionGraphResultNode::StaticClass();
		AnimGraphPlayAnimTask::StaticClass();
		AnimGraphStateMachineStateTask::StaticClass();
		AnimGraphTransitionTask::StaticClass();
		AnimGraphTransitionResultTask::StaticClass();
		SGraphTask::StaticClass();
		
		Character::StaticClass();
		GameModule::StaticClass();

		MaterialSeparateColorRGBNode::StaticClass();
		MaterialOutputNode::StaticClass();
		MaterialGetAssetNode::StaticClass();
		MaterialColorPickerNode::StaticClass();
		MaterialColorMixerNode::StaticClass();

		NodeEditorBlueprintNode::StaticClass();
		NodeEditorHintNode::StaticClass();
		NodeEditorTaskBase::StaticClass();
		NodeEditorTreeNode::StaticClass();
		NodeEditorVariableNode::StaticClass();
		NodeEditorSetVariableNode::StaticClass();
		SNodeEditorGetVariableTask::StaticClass();

		Entity::StaticClass();
	}
	
}

#endif
