name: CI(Windows)

on:
  push:
    branches: [ vulkan ]
  pull_request:
    branches: [ vulkan ]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
    
    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.5.5
      with:
        - optional_components: com.lunarg.vulkan.debug

    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.5.1

    - name: Generate Project Files
      run: premake5 vs2022

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build Solution
      run: msbuild -property:Configuration=Debug,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo Saturn.sln
